apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uclhc-storage
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
